name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dockerfile_lint:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run dockerfile_lint
        run: npx --cache .npx dockerfile_lint

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t tor-socks-proxy:${{ github.sha }} .
